name: github-actions
on:
  pull_request:
    types:
      - closed
env:
  pj_name: blocklist
  funcurl: ${{ secrets.API_URL }}
  repository_url: https://github.com/SlopeFinance/blocklist.git
jobs:
  update-blocklist:
#    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: update blocklist
        shell: bash
        run: |
          git clone ${{ env.repository_url }}
          [ -f ${{ env.pj_name }}/upload.sh ] && echo true || echo false
          bash -x ${{ env.pj_name }}/upload.sh
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
