name: learn-github-actions
on: [pull_request]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: copy file
        shell: bash
        run: | 
          # echo The username is ${{ inputs.username }}
          echo The PR was merged
          echo `pwd`
