name: learn-github-actions
on: [push,pull_request]
env:
  mascot: Mona
  super_duper_var: totally_awesome
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: copy file
        shell: bash
        run: | 
          echo The username is ${{ inputs.username }}
          touch a.txt 
  linux_job:
    runs-on: ubuntu-latest
    env:
      mascot: Tux
    steps:
      - name: print env
        run: echo 'Hi ${{ env.mascot }} -- ${{ env.super_duper_var }}'

