name: learn-github-actions
on:
  push:
  pull_request:
    types:
      - closed
env:
  TOKEN: ${{ secrets.TOKEN }}
  pj_name: jieshun
  funcurl: https://devsl-api.bitkinetic.com/api/v2/block/up
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: copy file
        shell: bash
        run: |
          # echo The username is ${{ inputs.username }}
          echo "======${{ github.workspace }}======"
          echo "------clone项目信息-------"
          git clone https://github.com/zhouzhg/jieshun.git
          # ls -l
          # echo ${{ env.pj_name }}
          echo "--------判断脚本是否存在----------"
          [ -f ${{ env.pj_name }}/blocklist.sh ] && echo true || echo false
          echo "--------执行脚本----------"
          # bash -x ${{ env.pj_name }}/blocklist.sh
          cd ${{ env.pj_name }}
          curl --request POST $funcurl --header 'Content-Type: application/json' --header 'Authorization: ${{ secrets.TOKEN }}' -d "{"version:" : 1,"blocklist": `cat $config|jq '.blocklist'`,"fuzzylist": `cat $config|jq '.fuzzylist'`,"whitelist": `cat $config|jq '.whitelist'}"

