name: learn-github-actions
on: [pull_request]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: copy file
        run: | 
          echo The username is ${{ inputs.username }}
          touch a.txt 
